export enum GameState {
	Boot = 'Boot',
	MainMenu = 'MainMenu',
	TableSetup = 'TableSetup',
	PostingBlinds = 'PostingBlinds',
	DealHoleCards = 'DealHoleCards',
	BettingPreflop = 'BettingPreflop',
	DealFlop = 'DealFlop',
	BettingFlop = 'BettingFlop',
	DealTurn = 'DealTurn',
	BettingTurn = 'BettingTurn',
	DealRiver = 'DealRiver',
	BettingRiver = 'BettingRiver',
	Showdown = 'Showdown',
	Payout = 'Payout',
	HandSummary = 'HandSummary',
	NextHandOrExit = 'NextHandOrExit',
}
